In [1]:
import os
import librosa
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Dense, Dropout, Flatten
from tensorflow.keras.utils import to_categorical

In [2]:
dataset_path = "dataset"

In [ ]:
#A filename looks like:03-01-05-02-02-01-12.wav
#The third number represents the emotion.


In [3]:
emotion_dict = {
    "01": "neutral",
    "02": "calm",
    "03": "happy",
    "04": "sad",
    "05": "angry",
    "06": "fearful",
    "07": "disgust",
    "08": "surprised"
}

In [5]:
features = []
labels = []

In [ ]:
for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.endswith(".wav"):
            file_path = os.path.join(root, file)
            emotion_code = file.split("-")[2]
            emotion = emotion_dict[emotion_code]
            audio, sample_rate = librosa.load(file_path, sr=None)
            #MFCC (Mel-Frequency Cepstral Coefficients) is a way to convert sound into numbers that a neural network can understand.
            mfcc = librosa.feature.mfcc(
                y=audio,
                sr=sample_rate,
                n_mfcc=40
            )
            mfcc = np.mean(mfcc.T, axis=0)
            features.append(mfcc)
            labels.append(emotion)

In [7]:
X = np.array(features)
y = np.array(labels)

In [8]:
print(X.shape)
print(y.shape)
print(y[:10])

(2880, 40)
(2880,)
['neutral' 'neutral' 'neutral' 'neutral' 'calm' 'calm' 'calm' 'calm'
 'calm' 'calm']


In [12]:
print(X[0])

[-7.26217224e+02  6.85414200e+01  3.29339767e+00  1.22053003e+01
  5.51027775e+00  1.36674099e+01 -2.98382831e+00  3.09802914e+00
 -3.31081343e+00 -1.56438410e+00 -7.86165237e+00 -2.12428164e+00
  2.84920406e+00 -2.66780639e+00  9.59020138e-01  1.62816632e+00
 -2.73668909e+00  2.54241079e-01  2.67537713e+00 -1.76116550e+00
 -1.88647425e+00 -9.75619972e-01 -3.79437208e-01  4.00272876e-01
 -3.04404378e+00 -2.90125823e+00 -1.09247930e-01 -8.63565266e-01
 -3.33326936e+00 -1.97846508e+00  4.57081556e-01 -1.39910972e+00
 -2.92685556e+00  1.39566725e-02 -4.90733981e-01 -5.70905566e-01
  4.03992198e-02 -1.20721734e+00 -1.59498167e+00 -1.43648744e+00]


In [11]:
print(X[0].size)

40


In [13]:
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [14]:
print(y[0:10])

[5 5 5 5 1 1 1 1 1 1]


In [15]:
y = to_categorical(y)

In [16]:
print(y[0:10])

[[0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]]


In [17]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [18]:
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

In [19]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2304, 40, 1)
(576, 40, 1)
(2304, 8)
(576, 8)
